# Generated by Django 3.1.6 on 2021-02-08 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_allocated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(blank=True, default='', max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('eta', models.DateField()),
                ('purchased_quantity', models.IntegerField()),
                ('order_lines', models.ManyToManyField(through='inventory.Allocation', to='inventory.OrderLine')),
            ],
        ),
        migrations.AddField(
            model_name='allocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.batch'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.orderline'),
        ),
    ]
