# Generated by Django 3.1.6 on 2021-02-08 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_allocated',
            field=models.DateField(default=datetime.datetime(2021, 2, 8, 1, 32, 46, 915425)),
        ),
    ]
