# Generated by Django 3.1.6 on 2021-02-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210208_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_allocated',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together={('batch', 'order_line')},
        ),
        migrations.AlterUniqueTogether(
            name='orderline',
            unique_together={('order_ref', 'sku', 'qty')},
        ),
    ]
