# Generated by Django 3.1.6 on 2021-02-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210221_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PBL', 'Public'), ('PRV', 'Private'), ('INA', 'Inactive')], default='PRV', max_length=3),
        ),
    ]
