# Generated by Django 3.1.6 on 2021-02-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_orderline_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('AWA', 'Public'), ('APV', 'Private'), ('CMP', 'Completed'), ('DRF', 'Draft'), ('ONH', 'Inactive'), ('VOI', 'Void')], default='DRF', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('AWA', 'Public'), ('APV', 'Private'), ('DRF', 'Draft'), ('ONH', 'Inactive'), ('PAI', 'Paid'), ('VOI', 'Void')], default='DRF', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('cost', models.IntegerField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='InboundShipmentLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, default=1)),
                ('inbound_shipment', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.inboundshipment')),
                ('purchase_order_line', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventory.purchaseorderline')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='inbound_shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.inboundshipment'),
        ),
    ]
