# Generated by Django 3.1.6 on 2021-02-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210224_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
