# Generated by Django 3.1.6 on 2021-02-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210224_0221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('AWA', 'Public'), ('APV', 'Private'), ('DRF', 'Draft'), ('ONH', 'Inactive'), ('PAI', 'Paid'), ('VOI', 'Void')], default='DRF', max_length=3),
        ),
    ]
