# Generated by Django 3.1.6 on 2021-02-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20210225_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('AWA', 'Public'), ('APV', 'Private'), ('DRF', 'Draft'), ('ONH', 'Inactive'), ('PAI', 'Paid'), ('VOI', 'Void')], default='DRF', max_length=3, null=True),
        ),
    ]
