# Generated by Django 3.1.6 on 2021-02-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210225_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100, null=True, unique=True),
        ),
    ]
