# Generated by Django 3.1.6 on 2021-03-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20210227_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='inbound_shipment',
        ),
        migrations.AddField(
            model_name='batch',
            name='purchase_order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.purchaseorderline'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(blank=True, choices=[('AWA', 'Awaiting Approval'), ('APV', 'Approved'), ('DRF', 'Draft'), ('ONH', 'On Hold'), ('PAI', 'Paid'), ('VOI', 'Void')], default='DRF', max_length=3, null=True),
        ),
    ]
