# Generated by Django 3.1.6 on 2021-04-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20210331_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='purchase_order_line',
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.batch')),
                ('purchase_order_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.purchaseorderline')),
            ],
        ),
    ]
