# Generated by Django 3.1.6 on 2021-04-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20210404_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='purchased_quantity',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='reception',
            name='batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.batch'),
        ),
    ]
