# Generated by Django 3.1.6 on 2021-04-25 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20210425_0451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('address2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='state',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='orderline',
            name='cost',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.address'),
        ),
    ]
