# Generated by Django 3.2 on 2021-05-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20210501_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('qty', models.IntegerField()),
                ('cost', models.FloatField(blank=True, default=0.0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.product')),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='sales_order_lines',
        ),
        migrations.RemoveField(
            model_name='inboundshipmentline',
            name='purchase_order_line',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='purchase_order_line',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='reference',
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='TransactionLineIn',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.transactionline')),
            ],
            bases=('inventory.transactionline',),
        ),
        migrations.CreateModel(
            name='TransactionLineOut',
            fields=[
                ('transactionline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.transactionline')),
            ],
            bases=('inventory.transactionline',),
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='sales_order_line',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='salesorderline',
            name='sku',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorder',
            name='transaction_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='transactionlinein_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.transactionlinein'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesorderline',
            name='transactionlineout_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.transactionlineout'),
            preserve_default=False,
        ),
    ]
