# Generated by Django 3.2 on 2021-05-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20210501_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='sales_order_line',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='inventory.salesorderline'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='sales_order_lines',
            field=models.ManyToManyField(through='inventory.Allocation', to='inventory.SalesOrderLine'),
        ),
        migrations.AddField(
            model_name='reception',
            name='purchase_order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='inventory.purchaseorderline'),
        ),
    ]
